-- =========================================================
-- DDL EDUTECH
-- =========================================================

-- =========================================================
-- 0) LIMPIEZA Y CREACIÓN DE ESQUEMA
-- =========================================================

BEGIN;

DROP SCHEMA IF EXISTS edutech CASCADE;
CREATE SCHEMA edutech;
SET search_path TO edutech;

COMMIT;


-- =========================================================
-- 1) TABLAS DE CATÁLOGO
-- =========================================================

BEGIN;

CREATE TABLE rol (
  id_rol      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_rol VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE nivel_curso (
  id_nivel_curso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_nivel   VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE categoria (
  id_categoria      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_categoria  VARCHAR(80) NOT NULL UNIQUE,
  descripcion       TEXT,
  esta_activa       BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE estado_curso (
  id_estado_curso     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_curso VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE tipo_video (
  id_tipo_video     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_tipo_video VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE tipo_recurso (
  id_tipo_recurso     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_tipo_recurso VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE moneda (
  id_moneda     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo_moneda CHAR(3) NOT NULL UNIQUE,
  nombre_moneda VARCHAR(50) NOT NULL UNIQUE,

  CONSTRAINT ck_moneda_codigo
    CHECK (codigo_moneda ~ '^[A-Z]{3}$')
);

CREATE TABLE estado_orden (
  id_estado_orden     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_orden VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_federativo (
  id_estado_federativo     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_federativo VARCHAR(80) NOT NULL UNIQUE
);

CREATE TABLE ciudad (
  id_ciudad             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_estado_federativo  INT NOT NULL,
  nombre_ciudad         VARCHAR(80) NOT NULL,

  CONSTRAINT fk_ciudad_estado_federativo
    FOREIGN KEY (id_estado_federativo)
    REFERENCES estado_federativo(id_estado_federativo)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT uq_ciudad_estado_nombre
    UNIQUE (id_estado_federativo, nombre_ciudad)
);

CREATE TABLE proveedor_pago (
  id_proveedor_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_proveedor  VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_pago (
  id_estado_pago     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_pago VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_webhook (
  id_estado_webhook     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_webhook VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_inscripcion (
  id_estado_inscripcion     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_inscripcion VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_examen (
  id_estado_examen     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_examen VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_intento (
  id_estado_intento     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_intento VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_solicitud_instructor (
  id_estado_solicitud_instructor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_solicitud        VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE estado_revision_curso (
  id_estado_revision_curso     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_revision_curso VARCHAR(30) NOT NULL UNIQUE
);

COMMIT;


-- =========================================================
-- 2) TABLAS DE USUARIOS, SOLICITUDES Y CURSOS
-- =========================================================

BEGIN;

CREATE TABLE usuario (
  id_usuario           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_rol               INT NOT NULL,
  nombre               VARCHAR(80) NOT NULL,
  apellido_paterno     VARCHAR(80) NOT NULL,
  apellido_materno     VARCHAR(80),
  correo               VARCHAR(150) NOT NULL,
  password_hash        VARCHAR(255) NOT NULL,
  telefono             CHAR(10),
  esta_activo          BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_registro       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_usuario_rol
    FOREIGN KEY (id_rol)
    REFERENCES rol(id_rol)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_usuario_telefono
    CHECK (telefono IS NULL OR telefono ~ '^[0-9]{10}$')
);

CREATE TABLE solicitud_instructor (
  id_solicitud_instructor        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario_solicitante         INT NOT NULL,
  id_usuario_revisor             INT,
  id_estado_solicitud_instructor INT NOT NULL,
  area_experiencia               VARCHAR(120) NOT NULL,
  experiencia                    TEXT NOT NULL,
  evidencia_url                  VARCHAR(255),
  motivo                         TEXT NOT NULL,
  comentario_revision            TEXT,
  fecha_solicitud                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_revision                 TIMESTAMP,

  CONSTRAINT fk_solicitud_usuario_solicitante
    FOREIGN KEY (id_usuario_solicitante)
    REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_solicitud_usuario_revisor
    FOREIGN KEY (id_usuario_revisor)
    REFERENCES usuario(id_usuario)
    ON DELETE SET NULL
    ON UPDATE CASCADE,

  CONSTRAINT fk_solicitud_estado
    FOREIGN KEY (id_estado_solicitud_instructor)
    REFERENCES estado_solicitud_instructor(id_estado_solicitud_instructor)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_solicitud_revision
    CHECK (
      (id_usuario_revisor IS NULL AND fecha_revision IS NULL)
      OR
      (id_usuario_revisor IS NOT NULL AND fecha_revision IS NOT NULL)
    )
);

CREATE TABLE curso (
  id_curso              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario            INT NOT NULL,
  id_nivel_curso        INT NOT NULL,
  id_estado_curso       INT NOT NULL,
  titulo                VARCHAR(150) NOT NULL,
  descripcion           TEXT NOT NULL,
  imagen_portada        VARCHAR(255),
  precio_mxn            NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  fecha_creacion        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_curso_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_nivel
    FOREIGN KEY (id_nivel_curso)
    REFERENCES nivel_curso(id_nivel_curso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_estado
    FOREIGN KEY (id_estado_curso)
    REFERENCES estado_curso(id_estado_curso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_curso_precio
    CHECK (precio_mxn >= 0)
);

CREATE TABLE curso_categoria (
  id_curso      INT NOT NULL,
  id_categoria  INT NOT NULL,

  CONSTRAINT pk_curso_categoria
    PRIMARY KEY (id_curso, id_categoria),

  CONSTRAINT fk_curso_categoria_curso
    FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_curso_categoria_categoria
    FOREIGN KEY (id_categoria)
    REFERENCES categoria(id_categoria)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE revision_curso (
  id_revision_curso        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_curso                 INT NOT NULL,
  id_estado_revision_curso INT NOT NULL,
  id_usuario_revisor       INT NOT NULL,
  comentario               TEXT,
  fecha_revision           TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_revision_curso
    FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_revision_estado
    FOREIGN KEY (id_estado_revision_curso)
    REFERENCES estado_revision_curso(id_estado_revision_curso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_revision_usuario_revisor
    FOREIGN KEY (id_usuario_revisor)
    REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

COMMIT;


-- =========================================================
-- 3) TABLAS DE CONTENIDO EDUCATIVO
-- =========================================================

BEGIN;

CREATE TABLE modulo (
  id_modulo    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_curso     INT NOT NULL,
  titulo       VARCHAR(150) NOT NULL,
  numero_orden INT NOT NULL,

  CONSTRAINT fk_modulo_curso
    FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT ck_modulo_numero_orden
    CHECK (numero_orden > 0),

  CONSTRAINT uq_modulo_curso_orden
    UNIQUE (id_curso, numero_orden)
);

CREATE TABLE leccion (
  id_leccion        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_modulo         INT NOT NULL,
  id_tipo_video     INT NOT NULL,
  titulo            VARCHAR(150) NOT NULL,
  numero_orden      INT NOT NULL,
  texto_descriptivo TEXT,
  url_video         VARCHAR(255) NOT NULL,
  duracion_segundos INT,
  esta_activa       BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_leccion_modulo
    FOREIGN KEY (id_modulo)
    REFERENCES modulo(id_modulo)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_leccion_tipo_video
    FOREIGN KEY (id_tipo_video)
    REFERENCES tipo_video(id_tipo_video)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_leccion_numero_orden
    CHECK (numero_orden > 0),

  CONSTRAINT ck_leccion_duracion
    CHECK (duracion_segundos IS NULL OR duracion_segundos >= 0),

  CONSTRAINT uq_leccion_modulo_orden
    UNIQUE (id_modulo, numero_orden)
);

CREATE TABLE recurso (
  id_recurso      INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_tipo_recurso INT NOT NULL,
  titulo          VARCHAR(150) NOT NULL,
  descripcion     VARCHAR(255),
  url_recurso     VARCHAR(255) NOT NULL,
  fecha_creacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_recurso_tipo
    FOREIGN KEY (id_tipo_recurso)
    REFERENCES tipo_recurso(id_tipo_recurso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE leccion_recurso (
  id_leccion   INT NOT NULL,
  id_recurso   INT NOT NULL,
  numero_orden INT NOT NULL,

  PRIMARY KEY (id_leccion, id_recurso),

  CONSTRAINT fk_leccion_recurso_leccion
    FOREIGN KEY (id_leccion)
    REFERENCES leccion(id_leccion)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_leccion_recurso_recurso
    FOREIGN KEY (id_recurso)
    REFERENCES recurso(id_recurso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_leccion_recurso_numero_orden
    CHECK (numero_orden > 0),

  CONSTRAINT uq_leccion_recurso_orden
    UNIQUE (id_leccion, numero_orden)
);

COMMIT;


-- =========================================================
-- 4) TABLAS DE COMPRA, ORDEN, PAGO Y WEBHOOK
-- =========================================================

BEGIN;

CREATE TABLE orden (
  id_orden             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  numero_orden         CHAR(20) NOT NULL,
  id_usuario           INT NOT NULL,
  id_moneda            INT NOT NULL,
  id_estado_orden      INT NOT NULL,
  total                NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  fecha_creacion       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_actualizacion  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_orden_usuario
    FOREIGN KEY (id_usuario)
    REFERENCES usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_orden_moneda
    FOREIGN KEY (id_moneda)
    REFERENCES moneda(id_moneda)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_orden_estado
    FOREIGN KEY (id_estado_orden)
    REFERENCES estado_orden(id_estado_orden)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT uq_orden_numero
    UNIQUE (numero_orden),

  CONSTRAINT ck_orden_total
    CHECK (total >= 0)
);

CREATE TABLE orden_detalle (
  id_orden_detalle INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden         INT NOT NULL,
  id_curso         INT NOT NULL,
  precio_unitario  NUMERIC(10,2) NOT NULL,

  CONSTRAINT fk_orden_detalle_orden
    FOREIGN KEY (id_orden)
    REFERENCES orden(id_orden)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_orden_detalle_curso
    FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_orden_detalle_precio
    CHECK (precio_unitario >= 0),

  CONSTRAINT uq_orden_detalle_curso
    UNIQUE (id_orden, id_curso)
);

CREATE TABLE datos_compra (
  id_orden                  INT PRIMARY KEY,
  nombre_contacto           VARCHAR(80) NOT NULL,
  apellido_paterno_contacto VARCHAR(80) NOT NULL,
  apellido_materno_contacto VARCHAR(80),
  correo_contacto           VARCHAR(150) NOT NULL,
  telefono_contacto         CHAR(10) NOT NULL,
  direccion                 VARCHAR(180),
  id_ciudad                 INT,
  codigo_postal             CHAR(5),

  CONSTRAINT fk_datos_compra_orden
    FOREIGN KEY (id_orden)
    REFERENCES orden(id_orden)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_datos_compra_ciudad
    FOREIGN KEY (id_ciudad)
    REFERENCES ciudad(id_ciudad)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_datos_compra_telefono
    CHECK (telefono_contacto ~ '^[0-9]{10}$'),

  CONSTRAINT ck_datos_compra_cp
    CHECK (codigo_postal IS NULL OR codigo_postal ~ '^[0-9]{5}$')
);

CREATE TABLE pago (
  id_pago           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden          INT NOT NULL,
  id_proveedor_pago INT NOT NULL,
  id_estado_pago    INT NOT NULL,
  id_pago_externo   VARCHAR(120),
  monto_pagado      NUMERIC(10,2) NOT NULL DEFAULT 0.00,
  fecha_pago        TIMESTAMP,

  CONSTRAINT fk_pago_orden
    FOREIGN KEY (id_orden)
    REFERENCES orden(id_orden)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_pago_proveedor
    FOREIGN KEY (id_proveedor_pago)
    REFERENCES proveedor_pago(id_proveedor_pago)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_pago_estado
    FOREIGN KEY (id_estado_pago)
    REFERENCES estado_pago(id_estado_pago)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_pago_monto
    CHECK (monto_pagado >= 0)
);

CREATE TABLE webhook_pago (
  id_webhook        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pago           INT NOT NULL,
  id_estado_webhook INT NOT NULL,
  tipo_evento       VARCHAR(100) NOT NULL,
  id_evento_externo VARCHAR(150) NOT NULL,
  contenido_evento  JSONB NOT NULL,
  fecha_recibido    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT fk_webhook_pago
    FOREIGN KEY (id_pago)
    REFERENCES pago(id_pago)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_webhook_estado
    FOREIGN KEY (id_estado_webhook)
    REFERENCES estado_webhook(id_estado_webhook)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT uq_webhook_evento_externo
    UNIQUE (id_evento_externo)
);

COMMIT;


-- =========================================================
-- 5) TABLAS DE INSCRIPCIÓN, PROGRESO, EXAMEN Y CERTIFICADO
-- =========================================================

BEGIN;

CREATE TABLE inscripcion (
  id_inscripcion          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_orden_detalle        INT NOT NULL,
  id_estado_inscripcion   INT NOT NULL,
  fecha_inscripcion       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_finalizacion      TIMESTAMP,

  CONSTRAINT fk_inscripcion_orden_detalle
    FOREIGN KEY (id_orden_detalle)
    REFERENCES orden_detalle(id_orden_detalle)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_inscripcion_estado
    FOREIGN KEY (id_estado_inscripcion)
    REFERENCES estado_inscripcion(id_estado_inscripcion)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT uq_inscripcion_orden_detalle
    UNIQUE (id_orden_detalle)
);

CREATE TABLE progreso_leccion (
  id_inscripcion INT NOT NULL,
  id_leccion     INT NOT NULL,
  completada     BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_completada TIMESTAMP,

  PRIMARY KEY (id_inscripcion, id_leccion),

  CONSTRAINT fk_progreso_inscripcion
    FOREIGN KEY (id_inscripcion)
    REFERENCES inscripcion(id_inscripcion)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_progreso_leccion
    FOREIGN KEY (id_leccion)
    REFERENCES leccion(id_leccion)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT ck_progreso_fecha
    CHECK (
      (completada = TRUE AND fecha_completada IS NOT NULL)
      OR
      (completada = FALSE AND fecha_completada IS NULL)
    )
);

CREATE TABLE examen (
  id_examen              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_curso               INT NOT NULL,
  id_estado_examen       INT NOT NULL,
  titulo                 VARCHAR(150) NOT NULL,
  descripcion            TEXT,
  tiempo_limite_minutos  INT NOT NULL,
  max_intentos           INT NOT NULL,
  calificacion_minima    NUMERIC(5,2) NOT NULL,
  cantidad_preguntas     INT NOT NULL,

  CONSTRAINT fk_examen_curso
    FOREIGN KEY (id_curso)
    REFERENCES curso(id_curso)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_examen_estado
    FOREIGN KEY (id_estado_examen)
    REFERENCES estado_examen(id_estado_examen)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT uq_examen_curso
    UNIQUE (id_curso),

  CONSTRAINT ck_examen_tiempo
    CHECK (tiempo_limite_minutos > 0),

  CONSTRAINT ck_examen_max_intentos
    CHECK (max_intentos > 0),

  CONSTRAINT ck_examen_calificacion
    CHECK (calificacion_minima >= 0 AND calificacion_minima <= 100),

  CONSTRAINT ck_examen_cantidad
    CHECK (cantidad_preguntas > 0)
);

CREATE TABLE pregunta (
  id_pregunta    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_examen      INT NOT NULL,
  texto_pregunta TEXT NOT NULL,
  esta_activa    BOOLEAN NOT NULL DEFAULT TRUE,

  CONSTRAINT fk_pregunta_examen
    FOREIGN KEY (id_examen)
    REFERENCES examen(id_examen)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE opcion_respuesta (
  id_opcion    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pregunta  INT NOT NULL,
  texto_opcion TEXT NOT NULL,
  es_correcta  BOOLEAN NOT NULL DEFAULT FALSE,

  CONSTRAINT fk_opcion_pregunta
    FOREIGN KEY (id_pregunta)
    REFERENCES pregunta(id_pregunta)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE intento_examen (
  id_intento        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_examen         INT NOT NULL,
  id_inscripcion    INT NOT NULL,
  id_estado_intento INT NOT NULL,
  numero_intento    INT NOT NULL,
  fecha_inicio      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_fin         TIMESTAMP,
  calificacion      NUMERIC(5,2),
  aprobado          BOOLEAN,

  CONSTRAINT fk_intento_examen
    FOREIGN KEY (id_examen)
    REFERENCES examen(id_examen)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_intento_inscripcion
    FOREIGN KEY (id_inscripcion)
    REFERENCES inscripcion(id_inscripcion)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_intento_estado
    FOREIGN KEY (id_estado_intento)
    REFERENCES estado_intento(id_estado_intento)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_intento_numero
    CHECK (numero_intento > 0),

  CONSTRAINT ck_intento_calificacion
    CHECK (calificacion IS NULL OR (calificacion >= 0 AND calificacion <= 100)),

  CONSTRAINT uq_intento_inscripcion_numero
    UNIQUE (id_inscripcion, numero_intento)
);

CREATE TABLE pregunta_intento (
  id_intento   INT NOT NULL,
  id_pregunta  INT NOT NULL,
  numero_orden INT NOT NULL,

  PRIMARY KEY (id_intento, id_pregunta),

  CONSTRAINT fk_pregunta_intento_intento
    FOREIGN KEY (id_intento)
    REFERENCES intento_examen(id_intento)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_pregunta_intento_pregunta
    FOREIGN KEY (id_pregunta)
    REFERENCES pregunta(id_pregunta)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT ck_pregunta_intento_orden
    CHECK (numero_orden > 0),

  CONSTRAINT uq_pregunta_intento_orden
    UNIQUE (id_intento, numero_orden)
);

CREATE TABLE respuesta_alumno (
  id_intento  INT NOT NULL,
  id_pregunta INT NOT NULL,
  id_opcion   INT NOT NULL,
  es_correcta BOOLEAN NOT NULL,

  PRIMARY KEY (id_intento, id_pregunta),

  CONSTRAINT fk_respuesta_pregunta_intento
    FOREIGN KEY (id_intento, id_pregunta)
    REFERENCES pregunta_intento(id_intento, id_pregunta)
    ON DELETE CASCADE
    ON UPDATE CASCADE,

  CONSTRAINT fk_respuesta_opcion
    FOREIGN KEY (id_opcion)
    REFERENCES opcion_respuesta(id_opcion)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE TABLE certificado (
  id_certificado    INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_inscripcion    INT NOT NULL,
  codigo_certificado CHAR(20) NOT NULL,
  fecha_emision     TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  url_certificado   VARCHAR(255),

  CONSTRAINT fk_certificado_inscripcion
    FOREIGN KEY (id_inscripcion)
    REFERENCES inscripcion(id_inscripcion)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT uq_certificado_inscripcion
    UNIQUE (id_inscripcion),

  CONSTRAINT uq_certificado_codigo
    UNIQUE (codigo_certificado)
);

COMMIT;


-- =========================================================
-- 6) TABLA OPCIONAL DE CONTACTO
-- =========================================================

BEGIN;

CREATE TABLE mensaje_contacto (
  id_mensaje_contacto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre              VARCHAR(80) NOT NULL,
  correo              VARCHAR(150) NOT NULL,
  asunto              VARCHAR(120) NOT NULL,
  mensaje             TEXT NOT NULL,
  fecha_envio         TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fue_atendido        BOOLEAN NOT NULL DEFAULT FALSE
);

COMMIT;


BEGIN;

CREATE UNIQUE INDEX ux_usuario_correo_lower
ON usuario (LOWER(correo));

CREATE INDEX idx_usuario_rol
ON usuario (id_rol);

CREATE INDEX idx_solicitud_solicitante
ON solicitud_instructor (id_usuario_solicitante);

CREATE INDEX idx_solicitud_revisor
ON solicitud_instructor (id_usuario_revisor);

CREATE INDEX idx_solicitud_estado
ON solicitud_instructor (id_estado_solicitud_instructor);

CREATE INDEX idx_curso_usuario
ON curso (id_usuario);

CREATE INDEX idx_curso_estado
ON curso (id_estado_curso);

CREATE INDEX idx_curso_nivel
ON curso (id_nivel_curso);

CREATE INDEX idx_revision_curso
ON revision_curso (id_curso);

CREATE INDEX idx_modulo_curso
ON modulo (id_curso);

CREATE INDEX idx_leccion_modulo
ON leccion (id_modulo);

CREATE INDEX idx_recurso_tipo
ON recurso (id_tipo_recurso);

CREATE INDEX idx_orden_usuario
ON orden (id_usuario);

CREATE INDEX idx_orden_estado
ON orden (id_estado_orden);

CREATE INDEX idx_orden_detalle_orden
ON orden_detalle (id_orden);

CREATE INDEX idx_orden_detalle_curso
ON orden_detalle (id_curso);

CREATE INDEX idx_datos_compra_ciudad
ON datos_compra (id_ciudad);

CREATE INDEX idx_pago_orden
ON pago (id_orden);

CREATE INDEX idx_pago_estado
ON pago (id_estado_pago);

CREATE UNIQUE INDEX ux_pago_externo_proveedor
ON pago (id_proveedor_pago, id_pago_externo)
WHERE id_pago_externo IS NOT NULL;

CREATE INDEX idx_webhook_pago
ON webhook_pago (id_pago);

CREATE INDEX idx_webhook_estado
ON webhook_pago (id_estado_webhook);

CREATE INDEX idx_inscripcion_estado
ON inscripcion (id_estado_inscripcion);

CREATE INDEX idx_inscripcion_orden_detalle
ON inscripcion (id_orden_detalle);

CREATE INDEX idx_progreso_leccion
ON progreso_leccion (id_leccion);

CREATE INDEX idx_pregunta_examen
ON pregunta (id_examen);

CREATE INDEX idx_opcion_pregunta
ON opcion_respuesta (id_pregunta);

CREATE INDEX idx_intento_examen
ON intento_examen (id_examen);

CREATE INDEX idx_intento_inscripcion
ON intento_examen (id_inscripcion);

CREATE INDEX idx_pregunta_intento_pregunta
ON pregunta_intento (id_pregunta);

CREATE INDEX idx_respuesta_opcion
ON respuesta_alumno (id_opcion);

COMMIT;


-- =========================================================
-- 8) FUNCIONES Y TRIGGERS
-- =========================================================

BEGIN;

CREATE OR REPLACE FUNCTION fn_set_fecha_actualizacion()
RETURNS TRIGGER AS $$
BEGIN
  NEW.fecha_actualizacion = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_usuario_fecha_actualizacion
BEFORE UPDATE ON usuario
FOR EACH ROW
EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_curso_fecha_actualizacion
BEFORE UPDATE ON curso
FOR EACH ROW
EXECUTE FUNCTION fn_set_fecha_actualizacion();

CREATE TRIGGER trg_orden_fecha_actualizacion
BEFORE UPDATE ON orden
FOR EACH ROW
EXECUTE FUNCTION fn_set_fecha_actualizacion();

COMMIT;


-- =========================================================
-- 9) VISTAS DE CONSULTA
-- =========================================================

BEGIN;

CREATE OR REPLACE VIEW vw_orden_resumen AS
SELECT
  o.id_orden,
  o.numero_orden,
  u.id_usuario,
  u.nombre || ' ' || u.apellido_paterno AS alumno,
  eo.nombre_estado_orden,
  m.codigo_moneda,
  o.total,
  o.fecha_creacion,
  COUNT(od.id_orden_detalle) AS total_cursos
FROM orden o
JOIN usuario u ON u.id_usuario = o.id_usuario
JOIN estado_orden eo ON eo.id_estado_orden = o.id_estado_orden
JOIN moneda m ON m.id_moneda = o.id_moneda
LEFT JOIN orden_detalle od ON od.id_orden = o.id_orden
GROUP BY
  o.id_orden,
  o.numero_orden,
  u.id_usuario,
  u.nombre,
  u.apellido_paterno,
  eo.nombre_estado_orden,
  m.codigo_moneda,
  o.total,
  o.fecha_creacion;

CREATE OR REPLACE VIEW vw_inscripcion_detalle AS
SELECT
  i.id_inscripcion,
  i.fecha_inscripcion,
  i.fecha_finalizacion,
  ei.nombre_estado_inscripcion,
  o.id_orden,
  o.numero_orden,
  alumno.id_usuario AS id_alumno,
  alumno.nombre || ' ' || alumno.apellido_paterno AS alumno,
  c.id_curso,
  c.titulo AS curso,
  instructor.id_usuario AS id_instructor,
  instructor.nombre || ' ' || instructor.apellido_paterno AS instructor
FROM inscripcion i
JOIN estado_inscripcion ei ON ei.id_estado_inscripcion = i.id_estado_inscripcion
JOIN orden_detalle od ON od.id_orden_detalle = i.id_orden_detalle
JOIN orden o ON o.id_orden = od.id_orden
JOIN usuario alumno ON alumno.id_usuario = o.id_usuario
JOIN curso c ON c.id_curso = od.id_curso
JOIN usuario instructor ON instructor.id_usuario = c.id_usuario;

COMMIT;

-- =========================================================
-- 10) VALIDACIÓN FINAL
-- =========================================================

SELECT
  (SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = 'edutech') AS total_tablas,
  (SELECT COUNT(*) FROM pg_indexes WHERE schemaname = 'edutech')                  AS total_indices,
  (SELECT COUNT(*) FROM information_schema.views WHERE table_schema = 'edutech')  AS total_vistas;

-- =========================================================
-- FIN DEL SCRIPT DDL
-- =========================================================
