-- Paso 27.7 - Solicitudes de instructor para panel administrador
-- Ejecutar solo si la base no tiene estas tablas/catálogos.

BEGIN;

CREATE TABLE IF NOT EXISTS edutech.estado_solicitud_instructor (
  id_estado_solicitud_instructor INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_estado_solicitud        VARCHAR(30) NOT NULL UNIQUE
);

INSERT INTO edutech.estado_solicitud_instructor (nombre_estado_solicitud)
VALUES ('pendiente'), ('aceptada'), ('rechazada')
ON CONFLICT (nombre_estado_solicitud) DO NOTHING;

CREATE TABLE IF NOT EXISTS edutech.solicitud_instructor (
  id_solicitud_instructor        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario_solicitante         INT NOT NULL,
  id_usuario_revisor             INT,
  id_estado_solicitud_instructor INT NOT NULL,
  area_experiencia               VARCHAR(120) NOT NULL,
  experiencia                    TEXT NOT NULL,
  evidencia_url                  VARCHAR(255),
  motivo                         TEXT NOT NULL,
  comentario_revision            TEXT,
  fecha_solicitud                TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_revision                 TIMESTAMP,

  CONSTRAINT fk_solicitud_usuario_solicitante
    FOREIGN KEY (id_usuario_solicitante)
    REFERENCES edutech.usuario(id_usuario)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,

  CONSTRAINT fk_solicitud_usuario_revisor
    FOREIGN KEY (id_usuario_revisor)
    REFERENCES edutech.usuario(id_usuario)
    ON DELETE SET NULL
    ON UPDATE CASCADE,

  CONSTRAINT fk_solicitud_estado
    FOREIGN KEY (id_estado_solicitud_instructor)
    REFERENCES edutech.estado_solicitud_instructor(id_estado_solicitud_instructor)
    ON DELETE RESTRICT
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_solicitud_solicitante
ON edutech.solicitud_instructor (id_usuario_solicitante);

CREATE INDEX IF NOT EXISTS idx_solicitud_revisor
ON edutech.solicitud_instructor (id_usuario_revisor);

CREATE INDEX IF NOT EXISTS idx_solicitud_estado
ON edutech.solicitud_instructor (id_estado_solicitud_instructor);

COMMIT;
