services:
  postgres:
    image: postgres:16
    container_name: edutech_postgres
    restart: always
    environment:
      POSTGRES_DB: bd_edutech
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - edutech_postgres_data:/var/lib/postgresql/data
      - ../database/sql/01_ddl_edutech.sql:/docker-entrypoint-initdb.d/01_ddl_edutech.sql:ro
      - ../database/sql/02_dml_edutech.sql:/docker-entrypoint-initdb.d/02_dml_edutech.sql:ro
      - ../database/sql/03_dcl_edutech.sql:/docker-entrypoint-initdb.d/03_dcl_edutech.sql:ro

volumes:
  edutech_postgres_data: